[workspace]
members = [
    "crates/salieri-audio",
    "crates/salieri-app",
    "crates/salieri-core",
    "crates/salieri-midi",
    "crates/salieri-sampler",
    "crates/salieri-tui",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
crossterm = "0.28"
ctrlc = "3"
midir = { version = "0.10", features = ["coremidi_send_timestamped"] }
ratatui = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
