use super::*;

use crate::workflows::write_bytes_atomically;

pub(crate) fn run_export_strudel(args: &StrudelExportArgs) -> Result<()> {
    let input_path = args
        .input_path
        .as_deref()
        .context("missing Strudel input path: usage is salieri export strudel INPUT [OUTPUT.js]")?;
    let song = load_project(input_path)?;
    let export = format_strudel_export(&song, args)?;
    if let Some(output_path) = &args.output_path {
        write_bytes_atomically(output_path, export.as_bytes())
            .with_context(|| format!("failed to write Strudel export {}", output_path.display()))?;
        println!("Wrote Strudel export to {}", output_path.display());
    } else {
        print!("{export}");
    }
    Ok(())
}

pub(crate) fn format_strudel_export(song: &Song, args: &StrudelExportArgs) -> Result<String> {
    let scope = resolve_strudel_scope(song, args)?;
    let diagnostics = strudel_diagnostics(song, &scope);
    let mut output = String::new();
    output.push_str("// Generated by Salieri Strudel export v1\n");
    output.push_str(&format!("// scope: {}\n", scope.label));
    output.push_str(&format!(
        "// tempo: bpm={} linesPerBeat={}\n",
        song.transport.bpm, song.transport.lines_per_beat
    ));
    output.push_str(&format!(
        "// patternLengths: {}\n",
        scope
            .segments
            .iter()
            .map(|segment| format!("{}={}", segment.label, segment.pattern.row_count()))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    output.push_str("// diagnostics:\n");
    if diagnostics.is_empty() {
        output.push_str("// - none\n");
    } else {
        for diagnostic in &diagnostics {
            output.push_str(&format!("// - {}\n", sanitize_comment(diagnostic)));
        }
    }
    output.push('\n');
    output.push_str(&format!(
        "setcps({}/60/{})\n\n",
        song.transport.bpm, song.transport.lines_per_beat
    ));
    output.push_str("stack(\n");
    for (track_index, track) in song.tracks.iter().enumerate() {
        let rendered = render_strudel_track(&scope, track_index);
        let comma = if track_index + 1 == song.tracks.len() {
            ""
        } else {
            ","
        };
        output.push_str(&format!(
            "  note(\"{}\").velocity(\"{}\")",
            rendered.notes, rendered.velocities
        ));
        if rendered.has_gain {
            output.push_str(&format!(".gain(\"{}\")", rendered.gains));
        }
        if rendered.has_pan {
            output.push_str(&format!(".pan(\"{}\")", rendered.pans));
        }
        output.push_str(&format!(
            ".s(\"{}\"){} // Track {:02}: {}\n",
            strudel_symbol(track_index, &track.name),
            comma,
            track_index + 1,
            sanitize_comment(&track.name)
        ));
    }
    output.push_str(")\n");
    Ok(output)
}

struct StrudelScope<'a> {
    label: String,
    segments: Vec<StrudelSegment<'a>>,
}

struct StrudelSegment<'a> {
    label: String,
    pattern: &'a Pattern,
}

struct RenderedStrudelTrack {
    notes: String,
    velocities: String,
    gains: String,
    pans: String,
    has_gain: bool,
    has_pan: bool,
}

fn resolve_strudel_scope<'a>(song: &'a Song, args: &StrudelExportArgs) -> Result<StrudelScope<'a>> {
    if args.sequence {
        let segments = song
            .sequence
            .iter()
            .enumerate()
            .map(|(position, pattern_id)| {
                let pattern = pattern_by_id(song, *pattern_id).with_context(|| {
                    format!(
                        "sequence position {} references missing pattern {}",
                        position + 1,
                        pattern_id.0
                    )
                })?;
                Ok(StrudelSegment {
                    label: format!("seq{:02}:{}", position + 1, pattern.name),
                    pattern,
                })
            })
            .collect::<Result<Vec<_>>>()?;
        return Ok(StrudelScope {
            label: "sequence".to_string(),
            segments,
        });
    }

    let pattern_numbers = if args.patterns.is_empty() {
        vec![args.pattern]
    } else {
        args.patterns.clone()
    };
    let segments = pattern_numbers
        .iter()
        .map(|pattern_number| {
            if *pattern_number == 0 {
                anyhow::bail!("--pattern and --patterns are 1-based");
            }
            let pattern = song
                .patterns
                .get(pattern_number - 1)
                .with_context(|| format!("pattern {pattern_number} does not exist"))?;
            Ok(StrudelSegment {
                label: format!("pattern{:02}:{}", pattern_number, pattern.name),
                pattern,
            })
        })
        .collect::<Result<Vec<_>>>()?;

    let label = if pattern_numbers.len() == 1 {
        format!("pattern {}", pattern_numbers[0])
    } else {
        format!(
            "patterns {}",
            pattern_numbers
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(",")
        )
    };
    Ok(StrudelScope { label, segments })
}

fn pattern_by_id(song: &Song, pattern_id: salieri_core::PatternId) -> Option<&Pattern> {
    song.patterns
        .iter()
        .find(|pattern| pattern.id == pattern_id)
}

fn render_strudel_track(scope: &StrudelScope<'_>, track_index: usize) -> RenderedStrudelTrack {
    let mut notes = Vec::new();
    let mut velocities = Vec::new();
    let mut gains = Vec::new();
    let mut pans = Vec::new();
    let mut has_gain = false;
    let mut has_pan = false;

    for segment in &scope.segments {
        for row in &segment.pattern.rows {
            let cell = row.cells.get(track_index);
            notes.push(note_token(cell));
            velocities.push(velocity_token(cell));
            has_gain |= cell.and_then(|cell| cell.volume).is_some();
            has_pan |= cell.and_then(|cell| cell.pan).is_some();
            gains.push(gain_token(cell));
            pans.push(pan_token(cell));
        }
    }

    RenderedStrudelTrack {
        notes: notes.join(" "),
        velocities: velocities.join(" "),
        gains: gains.join(" "),
        pans: pans.join(" "),
        has_gain,
        has_pan,
    }
}

fn strudel_diagnostics(song: &Song, scope: &StrudelScope<'_>) -> Vec<String> {
    let mut diagnostics = Vec::new();
    diagnostics.push(
        "Clip launcher slots are not exported because the current project model exposes patterns and sequence only."
            .to_string(),
    );
    if !song.samples.is_empty()
        || !song.sample_assignments.is_empty()
        || !song.instruments.is_empty()
        || !song.track_instrument_assignments.is_empty()
    {
        diagnostics.push(
            "Sampler, instrument, and sample assignment data are not embedded in the Strudel output."
                .to_string(),
        );
    }
    if song.transport.swing != 0.0 {
        diagnostics.push("Swing timing is not translated to Strudel.".to_string());
    }
    if song.tracks.iter().any(|track| track.muted || track.solo) {
        diagnostics.push("Track mute and solo state are not translated.".to_string());
    }
    if mixer_has_non_default_state(song) {
        diagnostics
            .push("Mixer gain, routing, sends, and native effects are not translated.".to_string());
    }
    if scope_cells(scope).any(cell_has_untranslated_cell_metadata) {
        diagnostics.push(
            "Instrument columns, delay, gate, tracker commands, and parameter locks are reported but not translated."
                .to_string(),
        );
    }
    if scope
        .segments
        .iter()
        .any(|segment| !segment.pattern.automation.is_empty())
    {
        diagnostics.push("Pattern automation lanes are not translated.".to_string());
    }
    if scope_cells(scope)
        .any(|cell| matches!(cell.note, Some(NoteEvent::NoteOff | NoteEvent::NoteCut)))
    {
        diagnostics.push("Note-off and note-cut events are emitted as rests.".to_string());
    }
    diagnostics
}

fn scope_cells<'a>(scope: &'a StrudelScope<'a>) -> impl Iterator<Item = &'a PatternCell> {
    scope
        .segments
        .iter()
        .flat_map(|segment| segment.pattern.rows.iter())
        .flat_map(|row| row.cells.iter())
}

fn cell_has_untranslated_cell_metadata(cell: &PatternCell) -> bool {
    cell.instrument.is_some()
        || cell.delay.is_some()
        || cell.gate.is_some()
        || cell.command.is_some()
        || cell.command2.is_some()
        || !cell.parameter_locks.is_empty()
}

fn mixer_has_non_default_state(song: &Song) -> bool {
    if (song.mixer.master_gain - 1.0).abs() > f32::EPSILON
        || !song.mixer.sends.is_empty()
        || !song.mixer.master_effects.is_empty()
    {
        return true;
    }
    song.mixer.tracks.iter().any(|track| {
        (track.gain - 1.0).abs() > f32::EPSILON
            || track.pan.abs() > f32::EPSILON
            || track.muted
            || track.solo
            || !track.sends.is_empty()
            || !track.effects.is_empty()
    })
}

fn note_token(cell: Option<&PatternCell>) -> String {
    match cell.and_then(|cell| cell.note) {
        Some(NoteEvent::Note { pitch }) => midi_note_name(pitch),
        Some(NoteEvent::NoteOff | NoteEvent::NoteCut) | None => "_".to_string(),
    }
}

fn velocity_token(cell: Option<&PatternCell>) -> String {
    match cell.and_then(|cell| cell.note) {
        Some(NoteEvent::Note { .. }) => {
            format_ratio(cell.and_then(|cell| cell.velocity).unwrap_or(0x7f))
        }
        Some(NoteEvent::NoteOff | NoteEvent::NoteCut) | None => "0.00".to_string(),
    }
}

fn gain_token(cell: Option<&PatternCell>) -> String {
    format_ratio(cell.and_then(|cell| cell.volume).unwrap_or(0x7f))
}

fn pan_token(cell: Option<&PatternCell>) -> String {
    format!(
        "{:.2}",
        f32::from(cell.and_then(|cell| cell.pan).unwrap_or(64)) / 127.0
    )
}

fn format_ratio(value: u8) -> String {
    format!("{:.2}", f32::from(value.min(0x7f)) / 127.0)
}

fn midi_note_name(pitch: u8) -> String {
    const NAMES: [&str; 12] = [
        "c", "cs", "d", "ds", "e", "f", "fs", "g", "gs", "a", "as", "b",
    ];
    let octave = i16::from(pitch) / 12 - 1;
    format!("{}{}", NAMES[usize::from(pitch % 12)], octave)
}

fn strudel_symbol(track_index: usize, track_name: &str) -> String {
    let suffix = track_name
        .chars()
        .flat_map(char::to_lowercase)
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect::<String>()
        .split('_')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("_");
    if suffix.is_empty() {
        format!("track_{:02}", track_index + 1)
    } else {
        format!("track_{:02}_{suffix}", track_index + 1)
    }
}

fn sanitize_comment(value: &str) -> String {
    value.replace(['\n', '\r'], " ").replace("*/", "* /")
}
